# Generated by Django 4.2.2 on 2023-09-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_collect_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
