# Generated by Django 4.2.2 on 2023-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_rename_title_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="recommend",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "一级"), (2, "二级"), (3, "三级"), (4, "四级"), (5, "五级")],
                default=1,
                verbose_name="推荐指数",
            ),
        ),
    ]
