# Generated by Django 4.2.2 on 2023-09-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_recommend"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="sequence",
            new_name="seq",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="cover",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
    ]
