# Generated by Django 4.2.2 on 2023-09-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_rete_comment_rate_alter_comment_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
