# Generated by Django 4.2.2 on 2023-09-16 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_recommend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0003_delete_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="更新时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                (
                    "content",
                    models.CharField(default="", max_length=500, verbose_name="评论内容"),
                ),
                (
                    "rate",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "好评"), (2, "中评"), (3, "差评")],
                        default=1,
                        verbose_name="评论级别",
                    ),
                ),
                (
                    "star",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "一星"), (2, "二星"), (3, "三星"), (4, "四星"), (5, "五星")],
                        default=1,
                        verbose_name="评论星级",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                        verbose_name="所属订单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="所属商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单评论",
                "verbose_name_plural": "订单评论",
                "db_table": "comment",
            },
        ),
    ]
