# Generated by Django 4.2.2 on 2023-09-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "待支付"),
                    (2, "待发货"),
                    (3, "配送中"),
                    (4, "待评价"),
                    (5, "已完成"),
                    (6, "已关闭"),
                ],
                default=1,
                verbose_name="订单状态",
            ),
        ),
    ]
