# Generated by Django 4.2.2 on 2023-09-19 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_sequence_banner_seq_and_more"),
        ("orders", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordergoods_set",
                to="products.product",
                verbose_name="商品id",
            ),
        ),
    ]
