# Generated by Django 4.2.2 on 2023-09-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rename_sequence_banner_seq_and_more"),
        ("orders", "0006_alter_orderproducts_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="商品id",
            ),
        ),
    ]
